name: flutter_problems
description: A new Flutter project.

dependencies:

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:

  # downloaded both mdpi (1x) and xxhdpi (3x)
  # https://github.com/google/material-design-icons/blob/master/alert/drawable-mdpi/ic_error_outline_black_36dp.png?raw=true
  # https://github.com/google/material-design-icons/blob/master/alert/drawable-xxhdpi/ic_error_outline_black_36dp.png?raw=true
    - assets/ic_error_outline_black_36dp.png

  # only downloaded xxhdpi (3x) from
  # https://github.com/google/material-design-icons/blob/master/alert/drawable-xxhdpi/ic_warning_black_36dp.png?raw=true
    - assets/ic_warning_black_36dp.png

  # downloaded xxhdpi (3x) image but added as a mdpi (1x)
  # https://github.com/google/material-design-icons/blob/master/alert/drawable-xxhdpi/ic_error_black_36dp.png?raw=true
    - assets/ic_error_black_36dp.png

  # Side effect of Option B
  # Asset bundle is not smart and shouldn't be, to allow smarter variants in the future
  # https://github.com/google/material-design-icons/blob/master/action/drawable-xxhdpi/ic_accessibility_black_36dp.png?raw=true
    - assets/3.0x/ic_accessibility_black_36dp.png  # ### <==== this is not the correct path =====>

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
